# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betted_score1', models.IntegerField()),
                ('betted_score2', models.IntegerField()),
                ('bettime', models.DateTimeField()),
                ('winner_in_case_of_draw', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bet_phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('playtime', models.DateTimeField()),
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score_team1', models.IntegerField(blank=True, null=True)),
                ('score_team2', models.IntegerField(blank=True, null=True)),
                ('extra_score_info', models.CharField(blank=True, max_length=10)),
                ('needs_winner', models.BooleanField()),
                ('winner_in_case_of_draw', models.IntegerField(blank=True, null=True)),
                ('gametype', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nr_teams', models.IntegerField()),
                ('bets_allowed_until', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('still_in_the_running', models.BooleanField(default=True)),
                ('bet_phases', models.ManyToManyField(blank=True, null=True, to='bets.Bet_phase')),
                ('phases', models.ManyToManyField(blank=True, null=True, to='bets.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='bet_phase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Phase'),
        ),
        migrations.AddField(
            model_name='bet_phase',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Player'),
        ),
        migrations.AddField(
            model_name='bet_game',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game'),
        ),
        migrations.AddField(
            model_name='bet_game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Player'),
        ),
    ]
