# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bet_phases',
            field=models.ManyToManyField(to='bets.Bet_phase'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phases',
            field=models.ManyToManyField(to='bets.Phase'),
        ),
    ]
